# Valid config file
# Fill in fields marked with '???'

test:
  teardown_installation: true  # Affects test_cse_server.py.
                               #   if true, delete all installation entities (even on test failure).
                               #   if false, do not delete installation entities (even on test success).
                               #   if this key is omitted, defaults to true.
  teardown_clusters: true      # Affects test_cse_client.py.
                               #   if true, delete test cluster (env.TEST_CLUSTER_NAME) on test failure.
                               #   if false, do not delete test cluster on test failure.
                               #   if this key is omitted, defaults to true.
                               # Successful client tests will not leave clusters up.
  test_all_templates: false    # Affects test_cse_client.py.
                               #   if true, tests cluster deployment on all templates found.
                               #   if false, tests cluster deployment only for first template found.
                               #   if this key is omitted, defaults to false.
  upgrade_template_repo_url: ''  #
  network: 'myNW'                    # org network within @vdc that will be used during testing
                                    #   Should have outbound access to the public internet
  org: 'deployment-org'                        # vCD org where all the test will be run
  storage_profile: '*'            # name of the storage profile to use while creating clusters on this org vdc
  vdc: 'deployment-vdc'                        # Org VDC powering the org

amqp:
  exchange: test-exchange # cse exclusive exchange used by amqp server
  host: bos1-vcd-sp-static-201-103.eng.vmware.com
  password: guest
  port: 5672
  prefix: vcd
  routing_key: test-routing-key-cse
  ssl: false
  ssl_accept_all: false
  username: guest
  vhost: /

vcd:
  api_version: '34.0'
  host: bos1-vcd-sp-static-204-205.eng.vmware.com
  log: true
  password: ca$hc0w
  port: 443
  username: administrator
  verify: false

vcs:
- name: vc1
  password: Welcome@123
  username: administrator@vsphere.local
  verify: false

service:
  enforce_authorization: false #need for local test
  listeners: 5
  log_wire: true
  telemetry:
    enable: true

broker:
  catalog: cse                          # public shared catalog within org where the template will be published
  default_template_name: ubuntu-16.04_k8-1.16_weave-2.6.0

                                        # name of the default template to use if none is specified
  default_template_revision: 2          # revision of the default template to use if none is specified
  ip_allocation_mode: pool              # dhcp or pool
  network: myNW                    # org network within @vdc that will be used during the install process to build the template
                                        #   Should have outbound access to the public internet
                                        #   CSE appliance doesn't need to be connected to this network
  org: '???'                            # vCD org that contains the shared catalog where the master templates will be stored
  remote_template_cookbook_url: https://raw.githubusercontent.com/vmware/container-service-extension-templates/master/template.yaml
  storage_profile: '*'                  # name of the storage profile to use when creating the temporary vApp used to build the template
  vdc: template-vdc                       # VDC within @org that will be used during the install process to build the template


# template_rules:
# - name: Rule1
#   target:
#     name: ubuntu-16.04_tkg-1.17_weave-2.5.2
#     revision: 1
#   action:
#     compute_policy: 'tkg-policy'
